# GitHub Actions Workflow para Build y Deploy de una Azure Function con Python 3.10
name: Build and deploy Python project to Azure Function App - adpfe

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # Ruta al proyecto (ajustar si tu función está en un subdirectorio)
  PYTHON_VERSION: "3.10" # Python 3.10 es soportado por Azure Functions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          echo "Running tests..."
          # Agrega aquí tus comandos de test, por ejemplo: pytest

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" "*.git/*" "*.github/*" "__pycache__/*" "*.pytest_cache/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: "adpfe" # Reemplaza con el nombre de tu Function App
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4114B09BB7BE42B980A36621660E180F }}
